if capital == 1 then print('a');;
if capital == 2 then print('b');;
if capital == 3 then print('c');;
if capital == 4 then print('d');;
if capital == 5 then print('e');;
if capital == 6 then print('f');;
if capital == 7 then print('g');;
if capital == 8 then print('h')
if capital == 9 then print('i')
if capital == 10 then print('j')
if capital == 11 then print('k')
if capital == 12 then print('l')
if capital == 13 then print('m')
if capital == 14 then print('n')
if capital == 15 then print('o')
if capital == 16 then print('p')
if capital == 17 then print('q')
if capital == 18 then print('r')
if capital == 19 then print('s')
if capital == 20 then print('t')
if capital == 21 then print('u')
if capital == 22 then print('v')
if capital == 23 then print('w')
if capital == 24 then print('x')
if capital == 25 then print('y')
if capital == 26 then print('z')
